[package]
name = "open-vote-network"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# Enable building WASM
[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
concordium-std = "2.0.0"
num-bigint = { version ="0.4", features = ["serde", "rand"] }
sha2 = "0.10.2"
rand = "0.8"

